"""
02 : Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
def fib_finder():
    a, b = 0, 1
    while True:
        yield a
        a, b = b , a+b

def limited_terms_fib(n):
    list_of_even = []

    for i in fib_finder():
        if i > n:
            break
        if not(i%2):
            print(i, " is even")
            list_of_even.append(i)
    return sum(list_of_even)

# print(limited_terms_fib(4000000))
