"""Triangular, pentagonal, and hexagonal
Problem 45 
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

def triangle():
	n = 286
	while True:
		if n >= 100000:
			return 
		yield int((n*(n+1))/2)
		n+=1

def penta_nums():
	n = 166
	while True:
		if n >= 100000:
			return 
		yield int((n*((3*n)-1))/2)
		n+=1

def hex_nums():
	n = 144
	while True:
		if n >= 100000:
			return 
		yield int(n*((2*n)-1))
		n+=1

if __name__ == '__main__':
	l_of_penta = [x for x in penta_nums()]
	l_of_hexa = [x for x in hex_nums()]

	for i in triangle():
		if (i in l_of_penta) and (i in l_of_hexa):
			print(i)
			break
